import { Inter } from "next/font/google";
import "./globals.scss";
import Navbar from "@/component/core/navbar/navbar";
import Footer from "@/component/core/footer";
import TimeProvider from "@/context/TimeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Prayer Time Surah and Dua",
  description: "Generated by Prayer Time Surah and Dua",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen flex flex-col bg-[rgba(76,2,3,.1)] ${inter.className}`}
      >
        <Navbar />
        <TimeProvider>{children}</TimeProvider>
        <Footer />
      </body>
    </html>
  );
}
