import { Inter } from "next/font/google";
import "./globals.scss";
import Navbar from "@/component/core/navbar/navbar";
import Footer from "@/component/core/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Namaz time schedule",
  description: "Generated by namaz time schedule",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`min-h-screen flex flex-col bg-[rgba(76,2,3,.1)] ${inter.className}`}>
        <Navbar />
        <div>{children}</div>
        <Footer/>
      </body>
    </html>
  );
}
